### ISSUE TITLE
Add filter option in top table

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Usagi#102]
Would be very useful if it would be possible to filter the rows based on the values in the table columns (as in Excel).

You can then focus on for example the Unchecked, but also if additional fields are added you could filter on those.

**Comment by PRijnbeek** [comment]
Search option would also be very useful.

**Comment by MaximMoinat** [comment]
Indeed a nice feature to have. Although this can also be achieved by sorting the codes on one of the fields. 

Also note that the previous sort is 'remembered'. So if you want to sort your Unchecked codes on frequency, then first sort on frequency and then sort on mapping status. After that, you only need to scroll to the first unchecked codes to start working through them.
