### ISSUE TITLE
Unpredictable behavior when change the set of "Additional info" columns

### ISSUE THREAD

**Issue by asivura** [OHDSI/Usagi#107]
Steps to reproduce:

1. Import file to Usagi and choose only one additional column with text values.
2. Do some mappings and export them
3. Import file to Usagi step 1 and choose few additional columns (in our case we had additional columns with numeric values) including the column from step 1.
4. Apply mapping from step 2 
5. Start randomly approve and unapprove records. After some period of time records start to disappear and the app freezes.

We use Usagi version 1.3.0 on MacOS 10.15.7
Java version: openjdk 15.0.1 2020-10-20

**Comment by MaximMoinat** [comment]
Hi @asivura. I haven't seen this behaviour before. 
For my understanding, why are you importing the same file twice? To continue working in the same file you can save the raw data and open it again later (which will automatically include all the additional columns).

**Comment by asivura** [comment]
Hi @MaximMoinat . We have to add additional records into the initial file from time to time. There is the reason why we are importing the new file and applying existing mappings. We decided to add additional columns when we imported the file and had the issue I described before. As a workaround, I added additional columns into our existing file with mappings manually with prefix "ADD_INFO:", but I think it would be great to fix it to avoid others having the same issue. It took us a few hours to understand why it is happening, and we lost some of the mapping results.

**Comment by MaximMoinat** [comment]
That helps. So you are using the [_File –> Apply previous mapping_](https://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:usagi#updating_an_usagi_mapping) functionality?

That is indeed something that might not be tested in all scenarios. Thanks for reporting!

**Comment by asivura** [comment]
Yes we use "File –> Apply previous mapping".

**Comment by MaximMoinat** [comment]
@asivura Was able to replicate. The bug occurs with the applied mapping contains new codes and has fewer additional columns. The issue is that additional columns are not read from the applied mapping file.

Working on a fix for the next release.
