### ISSUE TITLE
Apply previous mapping should not add codes

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Usagi#117]
If there are more codes in the previous file these are added, please make this optional.

I think the default should be only apply those that are in the current file you apply to.

**Comment by PRijnbeek** [comment]
I think it does not add indeed (since I do not see all new codes), however I did get the message x codes were added what does this mean then?

**Comment by MaximMoinat** [comment]
The intention is that the new codes are added, so we end up with a union of both. This is also what I observe in my test set.

In what case don't we want the new codes only occurring in the previous mapping?

**Comment by PRijnbeek** [comment]
I had a very unique situation where we received mappings from others that included codes that are not in our database but I agree in most cases this is what you want.
