### ISSUE TITLE
Error message null

### ISSUE THREAD

**Issue by hajarhomayouni** [OHDSI/Usagi#13]
Hi,

I want to try Usagi and I follwoed the instructions for its installation, but when I specify the vocabulary location and press "build index", it gives me an Error:null message with no more explanation. I specify the vocabulary location to my vocabulary csv files.
Any help would be really appreciated.

**Comment by schuemie** [comment]
Hi @hajarhomayouni ,

This sounds similar to an issue that others have reported, and that I haven't been able to reproduce myself. Can you just try again? That solved the problem for others.

**Comment by hajarhomayouni** [comment]
Yes, I don't see the error any more. it seems that indexes are built, and I see a message " please restart usagi to use the index". But when I restart Usagi, I see nothing in the panel. How can I force it to use the generated index?

**Comment by schuemie** [comment]
Well, the panels are supposed to be empty until you import a set of source codes. Are you saying you did that and none map to any concept?

**Comment by abhinava001** [comment]
Hi,

I am still facing this issue. I tried many times but this error is persisting. I am giving path to the location where all my vocabulary files in csv format exists. 

Any help would be really appreciated.

**Comment by samuelrosko** [comment]
I ran into a similar issue, but I was able to fix it after messing with the vocabulary files I downloaded from Athena. I don't know if you're having exactly the same issue that I was, but I got the null error that you are describing and couldn't find any help online to fix it either. Additionally, I am running Usagi on kubuntu 14.04. 

For me, for some reason the capitalization of the vocabulary files that Usagi wanted did not match the files that I got from Athena, so I ended up having to have two copies of each vocabulary .csv file in my folder for Usagi to successfully build indexes. By this, I mean that I needed both "concept.csv" and "CONCEPT.csv" in my folder, as Usagi was looking for "concept.csv" to continue but the file it actually used in building the indexes was "CONCEPT.csv". Having duplicate files, one with each name, was the only way I was able to get Usagi to work.

@schuemie, do you have any idea why this would be happening?

**Comment by schuemie** [comment]
Closing for now in the hope that the completely new import mechanisms doesn't have this intermittent problem. Will reopen if it does.
