### ISSUE TITLE
Select Multiple Concepts at Once and Change to Unmapped and Close Current Mapping Without Closing Program

### ISSUE THREAD

**Issue by anonymous34** [OHDSI/Usagi#133]
Currently, need to do this 1 by 1 and it is inefficient timewise.  This is need for concepts that have low match scores.

![image](https://user-images.githubusercontent.com/33704272/118531026-f69d6c00-b70a-11eb-9692-39ecd258a39a.png)

So would like to be able to select multiple concepts and remove the mapping when low matches scores.
So if I selected these the remove concept button should not be greyed out and only show one concept selection

![image](https://user-images.githubusercontent.com/33704272/118531216-35cbbd00-b70b-11eb-8ef1-221f0cb8015f.png)

When you have a mapping open, if you want to close it you cannot without exiting the whole program.  Would like a close open here:

![image](https://user-images.githubusercontent.com/33704272/118531609-a377e900-b70b-11eb-9ddc-bb155f784f5c.png)

**Comment by MaximMoinat** [comment]
For your first question, this is now supported. use `Edit-->Clear selected` 
![image](https://user-images.githubusercontent.com/17825660/118610563-2d7f8a80-b7bc-11eb-87e5-e48c42b6420d.png)

**Comment by MaximMoinat** [comment]
For your question on closing an opened mapping; what problem does this solve? The workflow implemented is that if you are done with the current mapping, you either open/import a new mapping with `File-->Open/Import` or close Usagi.

**Comment by anonymous34** [comment]
Thank you!
