### ISSUE TITLE
Index isn't building with all vocabularies

### ISSUE THREAD

**Issue by andrewDavisSensyne** [OHDSI/Usagi#135]
I am trying to use the most recent version of usagi but when I index the vocabularies from Athena I get an incomplete list. I am working with ICD10-CM values but the only ICD10 values that show up on usagi are ICD10-PCS. Is this an issue with the csv files that are downloaded from Athena having their delimiter being tabs instead of commas?

**Comment by MaximMoinat** [comment]
Usagi only makes an index for standard concepts. For an overview which source vocabularies are used as standard, please see [Table 5.2 in the Book of OHDSI](https://ohdsi.github.io/TheBookOfOhdsi/StandardizedVocabularies.html).
