### ISSUE TITLE
ICD10 not present in index

### ISSUE THREAD

**Issue by guneemwelloeux** [OHDSI/Usagi#139]
The ICD10 vocabulary does not show up as an option when searching for concepts, even if the data loaded into the index contains that vocabulary.

To reproduce:
1. Head to Athena and download the ICD10 vocab only
2. Startup Usagi and load the folder into the index with the downloaded csv files
3. Restart Usagi, and click on the dropdown "Filter by vocabulary", the ICD10 option is missing altogether

**Comment by MaximMoinat** [comment]
Usagi will only allow mapping to Standard concepts, which are the only valid targets according to the [OMOP conventions](https://ohdsi.github.io/CommonDataModel/cdm531.html#CONDITION_OCCURRENCE). For e.g. conditions, these will be mainly from the SNOMED vocabulary. All ICD10 codes are non-standard and can only be used as source concepts.

Usagi will use the ICD10 terms, if loaded, to improve the mapping of source codes to related standard conepts. 

What is your use case of using Usagi to map to ICD10 codes?
