### ISSUE TITLE
LOINC Codes 'unmatched' but they are in vocab v5 from Athena

### ISSUE THREAD

**Issue by smarinucci** [OHDSI/Usagi#144]
This might be a silly question but I am VERY new to Usagi and OHDSI in general.  I'm using Usagi v1.4.3 and the Vocabulary version v5 from Athena (LOINC last updated 22-Aug-2021).  I imported a file and quite a few LOINC codes were unmapped, however I was able to find the Concept ID in Athena for these codes.  Am I don't something wrong?
  Examples:  LOINC Codes 69689-8 and 69725-0.  Domain Observation. Concept IDs 40772115 and 40772149 respectively.
Thank you,  Sara

**Comment by MaximMoinat** [comment]
Hi @smarinucci. These concepts should indeed be available in Usagi after indexing a vocabulary download that includes LOINC.

Could you give some more information? e.g. what is the source code you are trying to map? what settings are you using when importing? can you find the given concept when searching on a manual query?
Screenshots would help as well.

**Comment by smarinucci** [comment]
Thank you so much @MaximMoinat!    
   Source Code: Its a list of LOINC codes and descriptions that are part of the Social Determinants of Health.
   Settings: Do you mean in the 'Search' portion of the screen?  Use source term, Filter standard concepts and include source terms.
   Manual query:  Do you mean finding an alternative in the Search Facility?  If so, the codes in question don't even show up in the Overview Table.  See screenshots below.  The Excel is the Source table.  This was generated manually, not by White Rabbit/Rabbit in a box.  I haven't figured those tools out yet.
![image](https://user-images.githubusercontent.com/98841388/152197300-1fc77d98-f087-4019-a3b0-08fb629b27f9.png)

![image](https://user-images.githubusercontent.com/98841388/152197374-b867a003-c9c0-412b-8e1f-e55185f13060.png)

Let me know if any other information would be helpful.  Thank you again!!!!  Sara

**Comment by MaximMoinat** [comment]
Hi @smarinucci, in your situation things are easier; you will not need Usagi to map LOINC codes! 

Usagi is used for coding systems not (yet) part of the OMOP Vocabulary. As you already discovered that LOINC codes exists as OMOP concepts, e.g. [40772115|Becoming easily annoyed or irritable in last 4 weeks [Reported.PHQ]](https://athena.ohdsi.org/search-terms/terms/40772115).

All you need to do is to lookup your LOINC codes in your OMOP Vocabulary tables. The first step is to set up an OMOP CDM database, and load the vocabulary tables. Then, the lookup can be done with a query like described here: https://ohdsi.github.io/CommonDataModel/sqlScripts.html#Source_to_Standard

**Comment by smarinucci** [comment]
@MaximMoinat  I was using this set of codes as a test to learn how to use Usagi since I knew what the end result should be.   It concerns me that Usagi didn't match all of my source codes to a concept when I know the equivalent concept exists.  Do you know why all of the source codes weren't matched?
   Side note, I did have a handful of codes that aren't loaded into our vocabulary yet that I did find using Athena. (Although I don't understand why that would happen. Shouldn't Athena match the most recent vocabulary released to us?)  Those codes were matched appropriately so I will test the Source to Concept mapping with those.
    Thank you for the link to those scripts. I greatly appreciate your assistance.

**Comment by MaximMoinat** [comment]
Note that Usagi is not matching on code, but on description. As you can see in your screenshot, where a full description is given, Usagi does return the right LOINC concept. Just a number (2,3,4 in your example) is not enough to find a target concept.

**Comment by smarinucci** [comment]
Ah. Ok.  I understand now.  Thank you so much for your help!!  I hope one day I'll know enough so that I can assist newcomers myself.

**Comment by MaximMoinat** [comment]
You're welcome. Good luck on your OHDSI journey!
