### ISSUE TITLE
STCM Date Export Format Option

### ISSUE THREAD

**Issue by anonymous34** [OHDSI/Usagi#145]
One of our ETL developers is requesting when the STCM file is exported, please export the date is in the following format:
01/01/2000.  

Currently the file exports in this format and the developer is having to change it every time because the database format is set differently in the database (format above)

1970-01-01,2099-12-31

**Comment by MaximMoinat** [comment]
For most databases the default date format is yyyy-mm-dd, and therefore that is what Usagi uses. 

Please refer to your database manual how to change this for importing dates in different formats. For instance, in postgres the date format can be changed with [`DateStyle (string)`](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-DATESTYLE)
