### ISSUE TITLE
Need help In CDM set up

### ISSUE THREAD

**Issue by umesh-clinakos** [OHDSI/Usagi#147]
We want the consulting services from one of the contributors to set up our custom CDM from the FHIR data we have. 

We have tried it our own with iteration and could not able to get throw it. Every time the converted data seems to be failing on the Atlas as soon as we connect it. Since we are very new to this so not sure how the mapping of rxnorm, NDC, and CPT code needs to be done with concept id using Usagi tool etc.

 If anybody is interested in helping us then can contact me on umesh.yadav@clinakos.com.

**Comment by MaximMoinat** [comment]
Hi @umesh-clinakos. For RxNorm, NDC, CPT, you will not need Usagi.

If you are looking for general OMOP consultancy or training, with a link with FHIR, I will follow-up over email.
