### ISSUE TITLE
Download Usagi issues

### ISSUE THREAD

**Issue by emmaleof** [OHDSI/Usagi#149]
Hello,

I downloaded Usagi earlier this week. I started importing the vocabularies yesterday and it was still running after 24 hours. I restarted my computer to close the app (as it wouldn't let me click out of it or force quit). When I went to reopen Usagi, it did not open and asked what application I would like to use to open it. It is now trying to open it as an Adobe PDF, which doesn't work. I also tried deleting the .jar file from my downloads and redownloading from the Releases tab, but it still wants to open as a PDF. Do you have suggestions on how to get it to properly download? Thanks!

**Comment by MaximMoinat** [comment]
Hi @emmaleof. Vocabulary loading can indeed take a long time, depending on the vocabulary subset you are loading. I would advice to download a small subset from Athena (e.g. only SNOMED) and try to index that with Usagi. If this still runs for more than 24 hours, then something else is wrong. Maybe your laptop has limited cpu and/or memory?

About opening with Adobe, that is probably a system setting. Right click -> open with might help, or using the command line to start Usagi (`java -jar Usagi-v1.4.3.jar`).

I am closing this issue.
