### ISSUE TITLE
csv mean comma separated files

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Usagi#15]
Just pointing out that csv stands for comma separated files.  However, it seems Usagi, insists on tab separated files with the csv extension.  I know the vocabulary distribution files match the confusing convention of having tab separated files with the csv extension.  Suggest that documentation make this clear.

**Comment by schuemie** [comment]
Usagi's own CSV files that are used for storing the mappings use comma delimiters. Only the Athena files are called CSV files but are tab delimited. I've tried to simply refer to them as 'the Athena files' to avoid confusion.
