### ISSUE TITLE
OMOP Documentation suggestion to tie in Usagi to source_to_concept_map

### ISSUE THREAD

**Issue by heschmidt04** [OHDSI/Usagi#158]
Hi Folks
While working to get OMOP database up and populated I didn't realize that Usagi was a tool that could help create a lookup table for extract, load, transform workflow. 

I opened an enhancement at https://github.com/OHDSI/CommonDataModel/issues/599 
And I wanted to cover all bases by opening an enhancement here. 

It would be great to add to the Usagi documentation the use cases/runbook/ddl for 

1. The DDL used by Polina and others for review tables 
2. The process with Usagi to help do diffs between new Athena Vocabulary editions and the previous version to keep concept codes up to date within a database over time. 
 
Via CHoRUS Bridge2AI, Polina and Jared have more context on how they are currently using the source_to_concept_map in their workflows. 

Thanks for your time and consideration.
Best, 
Heidi 
hschmidt@mgb.org

**Comment by MaximMoinat** [comment]
This link between Usagi and the STCM table is given [here](https://ohdsi.github.io/Usagi/usage.html#export-the-usagi-map-created) and more extensively in the Book of OHDSI: https://ohdsi.github.io/TheBookOfOhdsi/ExtractTransformLoad.html#export-the-usagi-map-created
