### ISSUE TITLE
Import error when frequency value too big

### ISSUE THREAD

**Issue by shreema26** [OHDSI/Usagi#159]
<img width="640" alt="usagi" src="https://github.com/OHDSI/Usagi/assets/135104476/daf95bb5-6f9d-422f-853b-a1a814552896">

Encountering an issue with the input string, resulting in an error, as seen in the attached screenshot. The same error persists for the first row of the description column in multiple CSV files.

**Comment by MaximMoinat** [comment]
See also #148. A very quick (and a bit dirty) fix is to preprocess the input file and report the frequency in thousands or millions.

**Comment by shreema26** [comment]
Hi @MaximMoinat 
I saw the solution in #148 where you have given solution that "The frequency is stored in an int, and the maximum value of a Java integer is 2^31-1 = 2,147,483,647. Probably any frequency exceeding this will raise the above error.

We should either change the data type to a big integer OR raise a more insightful error."
In my case no frequency is exceeding 2,147,483,647.

**Comment by MaximMoinat** [comment]
@janblom FYI: the issue is not about frequency value being too big, but input string being not numeric ('excision of lump').
<img width="446" alt="image" src="https://github.com/OHDSI/Usagi/assets/17825660/3c9c405a-e4f6-42ab-b4d3-b213aa80c2c5">
