### ISSUE TITLE
Support mapping to value_as_concept?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Usagi#16]
Sometimes a concept requires two mappings, which in the vocab is represented as both a 'maps to' and a 'maps to value' relationship. For example, the code could be 'Family history of breast cancer', which would map to the observation 'Family history' with as value the concept ID for breast cancer. It would be nice if Usagi somehow supports this.

**Comment by MaximMoinat** [comment]
Implemented since v1.4
