### ISSUE TITLE
Opening Mapping File Taking Over an Hour

### ISSUE THREAD

**Issue by anonymous34** [OHDSI/Usagi#161]
We have a physician helping to map order codes to OMOP concepts.  When he opens Usagi and does File > Open it is taking over 1 hour for Usagi to index the codes and completely open the file.  The version of Java he is using is 
Version 9.0.4 (build 9.0.4+ 11)  amd64
It also says Expiration Date 5/17/2018

I am able to open the same file into Usagi within seconds.  My java version is Version 8 Update 291 (build 1.8.0_291-b10).  

Any troubleshooting tips to help our physician index the codes faster when opening the file.  Can we configure something to help open faster?

**Comment by janblom** [comment]
As a first step, I would recommend installing a supported version of Java with long term support (LTS): 11 or 17 (or even version 8). Was Java 9.0.4. installed as part of another application? Then it might be wise to keep that version in place, and test Usagi with the newer version.

Other causes might lie in the environment where the user wants to use Usagi, e.g. are the files stored on a network share?  If that is the case, copy the files to the local computer, and test with those.

Hope this helps,
Jan

**Comment by anonymous34** [comment]
He installed Java 8 update 291 bit build 1.8.0_291-b10 with long term
support. This is the version I have and it opens instantly for me.  It is
still taking him over an hour to open.  Is there anyway we can get some
error or command line input?

**Comment by janblom** [comment]
There are no facilities in Usagi to obtain error details, unfortunately.

Could you share:

- the version of Usage that is used (if it is not v 1.4.3, please upgrade)
- the Operating System in use
- the way Usagi is started (by double-clicking or from the command line)

And if Usage is started by clicking, could you let the user test if starting Usagi from the command line makes any difference?

**Comment by anonymous34** [comment]
Hey thanks.  I took a second look where his Usagi was located.  And
actually was under a network to drive so I had him copy to the
C drive and then it opened instantly.

**Comment by janblom** [comment]
Hi,

thanks for sharing this, could be useful information for others.
I will close the issue.
