### ISSUE TITLE
Inconsistent export to source_to_concept_map behaviour

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/Usagi#18]
Sometimes I delete the target concepts and approve this mapping (it is a peculiar mapping, but in this case I want to capture that a certain concept doesn't map to anything in the vocabulary). 
It shows a mapping to the concept_id 0:
![image](https://cloud.githubusercontent.com/assets/17825660/22465905/3857c01c-e7be-11e6-9b6c-a4d533e4cf3a.png)

Then when I export this mapping with 'Export to source_to_concept_map', these approved mappings to concept_id 0 are _not_ exported. Can live with that, as it is a mapping to nothing.
However, when I save the raw mapping file and open it again, these mappings to 0 _are_ exported tot the source_to_concept_map.

Which one is the correct behaviour? Or is mapping to 'unmappable' something that should not be allowed at all?

**Comment by schuemie** [comment]
Should be fixed [here](https://github.com/OHDSI/Usagi/commit/1197c2083a7e4b04863c921c291b8a1f29e94568)
