### ISSUE TITLE
Building Indexes using Additional LOINC Information

### ISSUE THREAD

**Issue by CaptainCodeSet** [OHDSI/Usagi#21]
Greetings,

When attempting to build the indexes in Usagi, I check the box for Add Additional LOINC Information to Index. I have tried using LOINC version 2.54, 2.56, 2.58, and 2.59 csv files, but each time I get an error that says "Error: Field "COMMENTS" not found. 

Starting with version 2.50, Regenstrief is making column changes to the CSV file that include addition of new columns, removal of columns, and renaming of columns. The COMMENTS column was renamed to "DefinitionDescription" in version 2.52 of LOINC. 

I believe the build Index error is due to the change in CSV file structure. Is Usagi going to be updated to address these changes?

**Comment by schuemie** [comment]
Can you tell me which version of Usagi you're using? The [latest version](https://github.com/OHDSI/Usagi/releases/tag/v1.0.0) has been modified and should work with the latest version of LOINC.

**Comment by CaptainCodeSet** [comment]
Usagi 5.0.

I agree this is odd because it looks like the Athena files contain LOINC version 2.56 released in June 2016.

**Comment by CaptainCodeSet** [comment]
As a side note, I have tried building the indexes without selecting the add additional LOINC information option checked and the index build fine without any error displayed. Here is the error file that gets generated:

*** Generic error information ***
Message: Field "COMMENTS" not found
Time: Mar 3, 2017 9:20:26 AM
Processor type: pentium_pro+mmx pentium_pro pentium+mmx pentium i486 i386 i86
Available processors: 24
Maximum available memory: 1,013,645,312 bytes
Used memory: 4,436,224 bytes
Java version: 1.8.0_51
Java vendor: Oracle Corporation
OS architecture: x86
OS name: Windows 7
OS version: 6.1
OS patch level: Service Pack 1

*** Stack trace ***
org.ohdsi.utilities.files.Row.get(Unknown Source)
org.ohdsi.usagi.indexBuilding.BuildIndex$BuildThread.loadLoincInfo(Unknown Source)
org.ohdsi.usagi.indexBuilding.BuildIndex$BuildThread.run(Unknown Source)


*** Working folder contents ***
Directory of C:\Usagi-0.5.0

Usagi-0.5.0.zip                                                       13,968,615                   28-02-2017 09:21:32
.classpath                                                                 1,112                   28-02-2017 09:21:39
.gitignore                                                                    18                   28-02-2017 09:21:39
.project                                                                     364                   28-02-2017 09:21:39
LICENSE-2.0.html                                                          11,156                   28-02-2017 09:21:39
README.md                                                                  2,210                   28-02-2017 09:21:39
build.xml                                                                  2,247                   28-02-2017 09:21:39
Usagi_v0.5.0.jar                                                      15,937,629                   28-02-2017 09:43:32
.settings                                                                      0      <DIR>        01-03-2017 08:54:33
lib                                                                        4,096      <DIR>        01-03-2017 08:54:34
man                                                                            0      <DIR>        01-03-2017 08:54:34
src                                                                            0      <DIR>        01-03-2017 08:54:34
Athena_Vocab_20170228                                                      4,096      <DIR>        01-03-2017 09:05:48
LOINC                                                                          0      <DIR>        01-03-2017 09:21:33
mainIndex                                                                  4,096      <DIR>        01-03-2017 09:36:02
Error.txt                                                                  2,698                   03-03-2017 09:03:25
Error1.txt                                                                 2,819                   03-03-2017 09:07:14
Error2.txt                                                                     0                   03-03-2017 09:20:26

Available disc space: 25,834,008,576 bytes

**Comment by schuemie** [comment]
Please upgrade to the latest version of Usagi, where these problems should be solved (and which has some nice new features).

Note that the LOINC file is only used to get **additional information** about LOINC concepts, such as any comments and example units. LOINC itself is indeed part of the vocab.

**Comment by CaptainCodeSet** [comment]
Thank you Schuemie, will do.

**Comment by smarinucci** [comment]
@schuemie I am encountering this same error with Usagi v 1.4.3 and the LOINC last updated Aug-2021.  Is there a current fix or am I doing something incorrectly?  Thank you
