### ISSUE TITLE
GB English concepts appearing in mapping selection list for SNOMED CT

### ISSUE THREAD

**Issue by CaptainCodeSet** [OHDSI/Usagi#23]
Greetings,

I am using Usagi 1.0 and attempting to map some concepts. I noticed that one of the concepts was not available in the U.S. Edition of SNOMED CT.  Is there a way to filter out GB English concepts or to specifically load the U.S. Edition? 

Below is the example concept. The concept ID does not exist in the U.S. Edition and is making mapping very difficult as I may only map to concepts in the U.S. Edition of SNOMED CT

![usagi_gb_english_2](https://cloud.githubusercontent.com/assets/26167008/24369603/89849abe-12f2-11e7-933f-932a49b0a63a.png)
![usagi_gb_english](https://cloud.githubusercontent.com/assets/26167008/24369649/a95fda4c-12f2-11e7-8b85-c610ad18bdc1.png)

**Comment by schuemie** [comment]
"Home visit" (concept ID 4259432) is one of the Standard Concepts in the Vocabulary, and is therefore a valid target to map to. Could you elaborate a bit more on why some of the Standard Concepts are off-limits to you?

**Comment by CaptainCodeSet** [comment]
Schuemie,

This has to do with SNOMED CT language reference sets as well as national extensions content. 
National Extension perspective: Concepts in a national extension should be able for use for mapping only if USAGI is being used in that specific country. For example. the U.S. Extension is a reference set that contains U.S. specific concepts. Those concepts may only be used and should only be used in the U.S

Language Reference Set:  GB english descriptions should not be displayed when the preferred language is US English.  Again, when extracting concepts out of the Snomed CT RF2 files, you have to apply the language reference set to exclude any concepts that only conain a GB english description....if you are working in the United States or another country.

The concept example I provided only has a GB English description and does not have a US english value. If you go to the IHTSDO SNOMED CT brower, you have to select the UK Edition to see that term. If you select the U.S. edition and search for the concept id, it doesn't exist therefore it isn't available or valid for use in mapping in the U.S. Realm.

Does that make sense?
John

**Comment by CaptainCodeSet** [comment]
Also, the highlighted example in the screen shot is "Care Home Vist" which is concept 889311000000109, and NOT  "Home visit" (concept ID 4259432)

**Comment by CaptainCodeSet** [comment]
Sorry...but also looking at the USAGI screen. When working with SNOMED what is the difference between the concept_ID and the Concept_Code? 

Is one the SCTID assigned to the description and the the other the SCTID assigned to the concept, respectively?

**Comment by schuemie** [comment]
USAGI's purpose is to create mappings from various source code systems to OHDSI's [Standardized Vocabulary](http://www.ohdsi.org/web/wiki/doku.php?id=documentation:vocabulary). SNOMED happens to be one of the many vocabularies that comprise the Vocabulary. The concept ID is the Vocabulary Concept ID, a unique identifier to identify concepts across the vocabularies. The concept code is the identifier used by a vocabulary.

I'm sorry, but I still don't understand the issue. What is the purpose of a standard if the standard differs at different sites? Are you using Usagi for mapping to OHDSI's Vocabulary, or are you just trying to map to SNOMED?

**Comment by CaptainCodeSet** [comment]
If that is the case, then OHDSI needs to restrict the concepts that are available for mapping to the SNOMED CT international edition and only display concepts that have a U.S. English preferred Fully specified name (FSN) and/or Preferred term (PT). If the concept only has a GB english preferred FSN and preferred term, then the concept is only available in the UK national edition and will not be available for use internationally.

**Comment by schuemie** [comment]
@cgreich : do you know more about this?

**Comment by CaptainCodeSet** [comment]
Schuemie,

I am not sure if this will help or not. Attached is a MS SQL script that extracts the valid U.S. English concepts from the SNOMED CT Snapshot RF2 files. The table names are close enough to the RF2 specific files, that I think it will be easy to understand.
[SQL_SCRIPT_SCT_RF2.docx](https://github.com/OHDSI/Usagi/files/876791/SQL_SCRIPT_SCT_RF2.docx)


Thanks
John

**Comment by cgreich** [comment]
@CaptainCodeSet:

Not sure what you are trying to achieve. Why is it important to you whether or not English SNOMED concepts are available? The UK SNOMED is available to you as an OHDSI collaborator, you shouldn't have to worry. Unless you live in a country that has no generic SNOMED license. Unlikely.

We have International, British and Australian SNOMED all mixed together. SNOMED constantly goes through a process and eliminated duplications between those national versions. But we as OHDSI don't get in the way of that.

Let me know.

**Comment by CaptainCodeSet** [comment]
USGAI doesn't provide an indicator on the screen to indicate if a concept is specific to national extension. The U.S. is not allowed to use or map to concepts in the Australian or UK national extensions. Conversion Austrialia should not be mapping to a concept in the U.S. or UK national extension. The extension are just that, an nation specific extension of the international edition of SNOMED CT that contains concepts sepecific to that nation. 

Since there is no national extension deliniator dispalyed on USAGI, I can mistakenly map one of my local code to a SNOMED CT concept that is only available in the Australian national extension. That is not an allowed mapping.

HL 7 has struggled with this same issue. Concepts that are in a national extesnion MAY NOT appear as part of a published international standard document. Only concepts that are in the international edition are available for use internationally for every country.

I strongly suggest that OHDSI meet with representatives at IHTSDO or Jim Case at the national library of medice in the U.S. to gain a better understand on what is allowed / disallowed when it comes to inclusion of nation specitic extension concepts.

**Comment by cgreich** [comment]
@CaptainCodeSet:

Hang on here. OHDSI is not a US institution. It is a international collaborative of researchers all over the world. The vocabularies are redistributed with the knowledge of the local providers for the purpose of supporting OHDSI. It is up to every user to make sure they have the necessary licenses. There is no way for us to police that.

In your case, if you don't want non-international SNOMED concepts to show up in USAGI, there is no field in the database that indicates that. However, it's very easy to distinguish them: The long codes are the ones you want to avoid. The short ones are the good ones.

Let me know.

**Comment by CaptainCodeSet** [comment]
Cgreich,

I agree with you that there is no way to police the licensing, which is why I recommeded that OHDSI only distribute the international edition code set and not the UK and Australian national extension content.

We can't make a blanket statement of "The long codes are the ones you want to avoid" because when concept is created in a national extension and then promoted to the international edition, the concept ID remains the same, but it is still a valid concept for use at the international level. The only way you can truely exclude the concepts that are not allowed to be used outside of a specific nation is to only provide content from the international edition. 

It isn't the fact that I don't want the non-international content. It is the fact that I can't differentiate it from the international content and/or I can't filter it out of the window that displays the map candidate information so that it isn't selected by a mapper when it is inappropriate.

I am not entirely sure, but I think there may also be a licensing issue involved with packaging and distributing SNOMED CT in this manner? The U.S. isn't licensed to use anything other than the International edition and U.S. Extension, just as the U.K. isn't licensed to use anything but the International edition and the U.K. extension. etc. etc.

I understand this is an international data model, which is why I compared it to the international standards for interoperability being published by HL 7 as an example of what is and isn't allowed. I also understand that OHDSI isn't a U.S. based institution, which in this case I don't believe matters, as you still have to comply with IHTSDO licensing or provide the users a way to comply with the licensing. I am not certain of the best way to do that.

I am not an expert in IHTSDO licensing as I only have 2 certifications from IHTSDO, which is why I am recommending OHDSI open a discussion with IHTSDO regarding what is currently being distributed by OHDSI to determine if it is allowed and/or whether it is correct.

In my opinion, if you want to standardize your data internationally, then you have to restrict the available mapping options to only the concepts in the international edition. Any data that is captured in a national extension concept, that has not been promoted to the international edition, will only provide data from that 1 country which will skue the data in the model because other counters are not allowed to map to a concept that only exists in another country's national extension.

**Comment by CaptainCodeSet** [comment]
Cgreich,

I did some more checking. As long as their aren't special restrictions imposed by the UK and Australian national release centers their likely isn't a licensing issue with how OHDSI is distributing content.

On the technical side, as I have come to understand, there is a "risk" that by combining content from multiple national extensions you could end up with duplicate representations of the same concept from the different extensions. 

HL 7 FHIR wg has decided to only use international edition concepts or request that concept in the U.S. national extension be promoted to the international edition so that they do not encounter licensing restrictions imposed by the national release center in a given country that would prevent concepts for use.

Based on my understanding, I would still recommend that OHDSI restrict themselves to only concepts in the international edition. If there are specific concepts in either the UK or Australian national extensions that are needed, then the optimal route may be to follow suite with HL 7, and request that a representative from that country request the concept be prompted to the international edition. This route elimiates the need for any software modifications to USAGI, ensures all SNOMED CT concepts are turely available at the international level, eliminates the risk for duplicate representations of the same concept, and prevent data gathered under a national extension specific concept from skueing data internationally because that concept isn't available internationally.

I hope that helps better explain why this was flagged as an issue.

**Comment by cgreich** [comment]
Well, look. The folks using the codes are the ones who have to watch the license. And there are English and Australian folks. And the data they use contain those codes, or are mapped to them. For example there are Read Codes in CPRD and THIN, which are mapped to SNOMED UK codes, who are in the overall hierarchical structure of SNOMED. In other words, they have international ancestors. I can't take them out, because then these codes are no longer functional. 

Who are you btw? CaptainCodeSet isn't exactly a discriptive identifier. Or better, very discriptive, but not an identifier. :)

**Comment by CaptainCodeSet** [comment]
Cgreich,

Sorry for the poor choice of screen names. It was a nick name my previous manager hung on me that stuck. 

I am John Snyder, DTR, RDN and I work for Geisinger Health Systems in Danville, PA, USA. My background is I managed and/or implemented the use of standardized terminologies for the entire organization to meet meaningful use stage II requirements. Currently, I work in research managing the application of  standardized terminologies to our deidentified patient data model. 

Any SNOMED CT code in a national extension should ultimately link back to a supertype parent in the international edition. The international edition is a dependacy for all national extensions. It sounds like the read codes are UK specific codes that wouldn't be appropriate to promote to the international edition. 

Since there is already data associated with concepts that are only in the UK and/or Australian national extensions, it would seem the best option would be for USAGI to flag codes that are specific to a national extension. That means using the national extension refset to flag only those concepts that have not been promoted from the national extension to the international edition and then allow for these concepts to be filtered out of the map candidate window at the bottom of the screen.

Something to take into consideration is there is the standard (i.e. SNOMED) and then there is the implementation of that standandard (i.e. how the standard functions in our local environment).  Our EHR system, as well as most if not all in the U.S. will only ever load the U.S. Edition (i.e. International edition + U.S. Extension) for data capture. I would be surprised if this isn't true for other member countries. That means I  don't have concepts from any national extension, other than the U.S., in our system. We use EPIC as our EHR vendor and to the best of my knowledge, they don't support importing multiple national extensions.  For that reason, I can't map to a concept that exists in only a national extension from another member country because it would technically "break" a foreign key constraint in EHR  database.  

One odd question....why were only the UK and Austrialian national extensions merged? If this were going to consistent, would OHDSI have to merge all available naitonal extensions? (I am not implying this should be done, just curious how the decision was reached.)
 

I hope that helps.
Thanks
John

**Comment by cgreich** [comment]
Ah. John! Yes, I have seen you around here. Welcome. And the avatar names don't really help in a place like OHDSI. We should have clear names, or just use them.

I hear you. You want the codes to be flagged in some form. Currently, the vocabulary_id and concept_class_id don't do that. The reason we decided against having vocabularies "SNOMED-INT", "SNOMED-UK" etc. is simple: Historic artefact. In RxNorm we are doing it: RxNorm and RxNorm Extension. And since we are building the latter, we can license it to anyone in the world we want, and we do.

Can you put in a request in the [CDM/Vocab Working group](http://www.ohdsi.org/web/wiki/doku.php?id=documentation:next_cdm) for that? There, we can discuss the options and their consequences. To change the SNOMED vocabulary name without good consideration would be HUGE.

Why only UK and Australia: Like everything in OMOP: Strictly by use case. I think there is a German and Spanish SNOMED, but nobody has stepped up and asked for it. So, it doesn't happen. We all have day jobs, the OHDSI community work is for Saturdays and Sundays.

**Comment by CaptainCodeSet** [comment]
I totally understand....the volunteer work is in danager of taking over the life that is available outside of work. :-)

Yep, i will put in the ticket as I totally agree the impact could be signicant and needs to be considered

Thank you again for humoring the ticket.

**Comment by CaptainCodeSet** [comment]
To make sure I have the ticket in the correct place, do you want me to open a ticket under https://github.com/OHDSI/Athena/issues or is there some place else? I looked at the link, but I don't have an account on the ODHSI site and don't see a place to add the ticket?

**Comment by cgreich** [comment]
Why don't you put it here: http://www.ohdsi.org/web/wiki/doku.php?id=documentation:next_cdm. Click on the last one in the "Need Preparation" table and get going. You need the proposal, and the use cases, adn the rationale.

**Comment by CaptainCodeSet** [comment]
Sorry, but when I go to the page and try to log in with my github credientials I get the following error:

Self-Registration is currently disabled or conf/users.auth.php is not writable. Please ask your DokuWiki administrator to create your account manually.

I don't have a ODHSI user account? 

uummmm.....Help?

**Comment by leeevans** [comment]
@CaptainCodeSet  I'm the OHDSI forum and wiki admin.

Please create an account on the OHDSI forum here:
http://forums.ohdsi.org/
and then send me a private message with your email address & I'll setup an OHDSI wiki account for you.

**Comment by CaptainCodeSet** [comment]
@leeevans: My email is jwsnyder@geisinger.edu
