### ISSUE TITLE
Indexing error by specifying location of Usagi vocabulary file

### ISSUE THREAD

**Issue by mircom2** [OHDSI/Usagi#25]
After installing Usagi, Vocabulary Rebuild index operation will be stopped while the following error occurs during operation.
Error content: Error: For input string: "23140nitial treatment day"

If you know anything about this, I would like to ask for help.

**Comment by schuemie** [comment]
Could you provide some more information? What version of Usagi did you use? What version of the vocabulary did you use (when was it downloaded, what subsets did you select)? Did the error appear right away when building the index?
