### ISSUE TITLE
Road Traffic Accident == Renal Tubular Acidosis?

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Usagi#30]
@schuemie , 

Found an odd USAGI pairing that I thought you might like to see:
![image](https://user-images.githubusercontent.com/6305439/27986937-1f5b8444-63d4-11e7-8ac3-3a217a987856.png)

[EXAMPLE ROW FOR USAGI.xlsx](https://github.com/OHDSI/Usagi/files/1133074/EXAMPLE.ROW.FOR.USAGI.xlsx)

Usagi thought "Road Traffic Accident" was 100% match to "Renal Tubular Acidosis".

Used USAGI v1.0.2 and Vocabulary 20170503.  Filtered to standard concepts, include source terms, and filtered by domain condition.

**Comment by schuemie** [comment]
I don't recall ever releasing a v.1.0.2. Can you confirm the problem still exists in v1.1.1?

**Comment by ericaVoss** [comment]
Tested in v1.1.1 and the issue still exists.

![image](https://user-images.githubusercontent.com/6305439/28118223-3cddb368-66de-11e7-8884-be1b22e70be0.png)

**Comment by schuemie** [comment]
I see now: ROAD TRAFFIC ACCIDENT (concept ID 45935538) maps to Renal tubular acidosis (concept ID 4070448) in the vocab. Even though the mapping is marked as valid, the first concept is not. 

I've changed Usagi to ignore all invalid concepts. Please fetch the [latest release](https://github.com/OHDSI/Usagi/releases/tag/v1.1.2) and rebuild the index to make the problem go away.

**Comment by dimshitc** [comment]
Yeah, it's CIEL, and it was given by source. we'll be fixed in the future.

**Comment by ericaVoss** [comment]
Looking much better in V1.1.2

![image](https://user-images.githubusercontent.com/6305439/28215973-d01d2898-687d-11e7-817f-323201aa1e3e.png)

**Comment by schuemie** [comment]
Thanks! Note that a perfect match can be found, but with concept_class_id = 'Observation'

**Comment by cgreich** [comment]
Sounds like one of those measurement/condition/observation overlaps.
