### ISSUE TITLE
Matching

### ISSUE THREAD

**Issue by MelaniePhilofsky** [OHDSI/Usagi#31]
I'm not sure if this is an issue or just a lack of understanding. I am using Usagi to map my uncoded provider specialty source concepts to the Provider Specialty domain. The string "Hepatology" did not return "Allopathic & Osteopathic Physicians, Internal Medicine, Hepatology" concept id = 38003876 as a top potential match. It had a match score = 0.37. Please help me understand this better.

![image](https://user-images.githubusercontent.com/22457958/28578931-263114ca-7129-11e7-90b7-21a864ec446b.png)

Thanks,
Melanie

**Comment by schuemie** [comment]
Usagi uses simple string similarity as match score. The string "Allopathic & Osteopathic Physicians, Internal Medicine, Hepatology" has many characters that are not matching "Hepatology", hence the low matching score.

Judging by your screenshot, you are using a rather old version. I recommend updating to the [latest version](https://github.com/OHDSI/Usagi/releases/tag/v1.1.2). This version not only has an improved matching algorithm, it also provides additional valuable information about the target concepts such as the number of parent and children concepts. You will need to rebuild the index.
