### ISSUE TITLE
Trouble Starting Usagi

### ISSUE THREAD

**Issue by samksoon** [OHDSI/Usagi#32]
I extracted and openened Usagi.jar, and then chose a vocabulary folder, but after that the screen has looked like this for quite a long period of time. Did I do something wrong?
![image](https://user-images.githubusercontent.com/11728043/28797393-25f5ffd0-760f-11e7-87ea-8733803386d4.png)

**Comment by schuemie** [comment]
Hi @samksoon ,

This should take about 10-15 minutes, depending mostly on how fast your harddisk is. Just  to be sure: are both the Athena files and the folder containing the Usagi jar on your local drive? It will take forever if you want to do this on a network drive.
