### ISSUE TITLE
Issues opening Usagi

### ISSUE THREAD

**Issue by lecksicon** [OHDSI/Usagi#35]
Hi, I've downloaded the Athena Vocabulary and tried to start Usagi so that it can build the index. However, when I point to the folder location of the Vocabulary, Usagi gives me an error saying that it can't find the CONCEPT.csv file even though it's in there. Am I doing something wrong?

**Comment by schuemie** [comment]
Sorry to hear that. I'm not sure what the problem is. Did you unzip the Athena file? Have you tried putting Usagi and the vocab files in the same folder?
