### ISSUE TITLE
Question About Matching Concepts

### ISSUE THREAD

**Issue by anonymous34** [OHDSI/Usagi#36]
Question, do we need to have the vocabulary files in the Usagi directory for any matching to concepts to work?  I just imported the source codes with the code, name, and frequency and nothing was mapped to a concept.  If so, which vocabulary files are needed and where can I get the most recent version of the vocabulary?  Thank you.

**Comment by schuemie** [comment]
Yes, you need to download the vocabulary from [ATHENA](https://athena.odysseusinc.com/search-terms/terms). (Make sure you include the MedDRA vocabulary, which is turned off by default but most people use anyway).

Then, when you start Usagi for the first time you should be prompted for the vocabulary files. Usagi will create a search index (this will take up to 15 minutes), after which you no longer need the vocabulary files.

**Comment by anonymous34** [comment]
Thanks, so I get a couple errors when I:
1) try to run java -jar cpt4.jar 5
It says Update failed.  UMLS web-API crashed
2) Tried the build the index
*** Generic error information ***
Message: null
Time: Dec 11, 2017 5:11:58 PM
Processor type: amd64
Available processors: 8
Maximum available memory: 3,790,077,952 bytes
Used memory: 47,129,584 bytes
Java version: 1.8.0_152
Java vendor: Oracle Corporation
OS architecture: amd64
OS name: Windows 7
OS version: 6.1
OS patch level: Service Pack 1

*** Stack trace ***
org.ohdsi.usagi.indexBuilding.ReadAthenaFile$AthenaFileIterator.<init>(Unknown Source)
org.ohdsi.usagi.indexBuilding.ReadAthenaFile.iterator(Unknown Source)
org.ohdsi.usagi.indexBuilding.BerkeleyDbBuilder.loadConcepts(Unknown Source)
org.ohdsi.usagi.indexBuilding.BerkeleyDbBuilder.buildIndex(Unknown Source)
org.ohdsi.usagi.indexBuilding.IndexBuildCoordinator$BuildThread.run(Unknown Source)


*** Working folder contents ***
Directory of C:\Usagi\Usagi

Usagi_v1.1.3.jar                                                      19,144,870                   07-11-2017 07:31:18
Usagi-1.1.3                                                                4,096      <DIR>        10-11-2017 11:31:21
dx_frequencies_for_all_encounters.csv                                 17,737,869                   06-12-2017 01:24:25
DOMAIN.csv                                                                 1,213                   08-12-2017 06:01:03
CONCEPT_CLASS.csv                                                         13,271                   08-12-2017 06:01:03
CONCEPT_CPT4.csv                                                         917,449                   08-12-2017 06:01:03
CONCEPT_ANCESTOR.csv                                               2,621,882,537                   08-12-2017 06:01:30
RELATIONSHIP.csv                                                          31,732                   08-12-2017 06:01:31
CONCEPT_SYNONYM.csv                                                  518,890,995                   08-12-2017 06:01:35
VOCABULARY.csv                                                             8,426                   08-12-2017 06:01:35
CONCEPT_RELATIONSHIP.csv                                           1,576,828,862                   08-12-2017 06:01:46
DRUG_STRENGTH.csv                                                    134,650,423                   08-12-2017 06:01:47
cpt.bat                                                                       30                   08-12-2017 06:01:47
cpt.sh                                                                        32                   08-12-2017 06:01:47
lib                                                                            0      <DIR>        08-12-2017 06:01:47
readme.txt                                                                   475                   08-12-2017 06:01:47
cpt4.jar                                                                 592,710                   08-12-2017 06:01:47
Reconstitute_cpt_4_error.PNG                                              13,009                   11-12-2017 10:34:04
lib_usagi                                                                      0      <DIR>        11-12-2017 04:50:58
Error.txt                                                                  3,894                   11-12-2017 04:57:10
Error1.txt                                                                 4,134                   11-12-2017 04:59:51
CONCEPT.csv                                                                    0                   11-12-2017 05:11:09
vocabularyVersion.txt                                                         16                   11-12-2017 05:11:58
sleepyCat                                                                  4,096      <DIR>        11-12-2017 05:11:58
Error2.txt                                                                     0                   11-12-2017 05:11:58

Available disc space: 184,538,632,192 bytes

**Comment by schuemie** [comment]
My guess is that the Usagi error is caused by the CPT script crashing. The CONCEPT.csv file appears to be corrupt. I suggest deleting all .csv files, re-extracting them from the zip file. and trying to rerun the CPT script.

**Comment by anonymous34** [comment]
Okay, I was able to capture the error output from just running the cpt.bat.  It says this

Exception in thread "main" java.lang.NoClassDefFoundError: com/opencsv/CSVParser
	at org.odhsi.utils.cpt.Application.upsertCpt4Data(Application.java:59)
	at org.odhsi.utils.cpt.Application.main(Application.java:46)
Caused by: java.lang.ClassNotFoundException: com.opencsv.CSVParser
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

So sounds like the script needs to be fixed and then it should work.  By the way, is the concept file supposed to be empty before this happens?

**Comment by schuemie** [comment]
Nope, the concept file should contain all the non-CPT4 concepts.

Would you mind posting the issue with cpt.bat on the [Athena issue tracker](https://github.com/OHDSI/Athena/issues)?

Maybe try and download from Athena again? It seems as though something went wrong there.

**Comment by anonymous34** [comment]
I created a post here and have not gotten a response.

https://github.com/OHDSI/Athena/issues/14
