### ISSUE TITLE
UTF-8 vocabulary files

### ISSUE THREAD

**Issue by 18818569575** [OHDSI/Usagi#37]
In Usagi, it is restricted to parse ISO-8859-1 vocabulary files, thus vocabulary files in some languages are not support, such as Chinese. I try to change the ISO-8859-1 to UTF-8 and can parse Chinese vocabulary successfully in this fork
https://github.com/18818569575/Usagi/commit/51ddd4dda887cbdce3c40513049984b7f087d63e
But I did not test it thoroughly. So is it OK to use UTF-8 encoding and maybe Usagi can be used in many other languages?

**Comment by schuemie** [comment]
Thanks for bringing this up. It seems [UTF-8 is also the standard for ATHENA](http://forums.ohdsi.org/t/utf-8-characters-not-translating-to-vocabularies/3195). I [copied your changes](https://github.com/OHDSI/Usagi/commit/179479750c5ac262b01248d753e0a1771d5bc9a9) and made a [new release](https://github.com/OHDSI/Usagi/releases/tag/v1.1.5).

I tested it a bit, and it seems to be working well. At least 'Ménière's disease' is now displayed properly!
