### ISSUE TITLE
Parallel execution in "Import codes" function

### ISSUE THREAD

**Issue by 18818569575** [OHDSI/Usagi#40]
The "Import codes" function is now a single thread process and thus is time-consuming. I think it could be done in a parallel way and implement a multi-thread version https://github.com/18818569575/Usagi/commit/2287df5a5608a2a499f511e6e8135a047356abe8
It can reduce a lot of processing time depending on the cores of the computer. Please help to review or test the code before it can be merged into the main repository.

**Comment by schuemie** [comment]
I think that is an excellent idea. Would you mind creating a pull request for that?

And could you also include [these fixes](https://github.com/18818569575/Usagi/commit/8ef78bf75fa67f85ee02078fa7bf5fb78fc68642) you made?

**Comment by schuemie** [comment]
Thanks! Now included in the [latest release](https://github.com/OHDSI/Usagi/releases/tag/v1.1.6).
