### ISSUE TITLE
filter by multiple entities

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Usagi#42]
It would be nice to be able to filter out by several vocabularies, domain and classes.

For example when we map the list of procedures
we basically need
vocabulary_id in ('SNOMED', 'LOINC')
domain_id in ('Procedure', 'Measurement', 'Observation')

**Comment by schuemie** [comment]
Please check out the [latest release](https://github.com/OHDSI/Usagi/releases/tag/v1.1.6),
