### ISSUE TITLE
Need Help With Mapping and Building Usagi Index

### ISSUE THREAD

**Issue by anonymous34** [OHDSI/Usagi#43]
You would think that gender codes would be easy to map.  Considering that these values are available in the concept table

8532	FEMALE	Gender	Gender	Gender	S	F	19700101	20991231	
8507	MALE	Gender	Gender	Gender	S	M	19700101	20991231	
8521	OTHER	Gender	Gender	Gender		O	19700101	20140731	D
8570	AMBIGUOUS	Gender	Gender	Gender		A	19700101	20140731	D
8551	UNKNOWN	Gender	Gender	Gender		U	19700101	20140731	D

Why is the Usagi tool not picking the F and M concepts?  Something does not seem right with this.  
![usagi_gender](https://user-images.githubusercontent.com/33704272/38285908-195c7ea8-3788-11e8-9f7f-6b3f48c1bbbf.JPG)

See how my configuration was not able to map anything after clicking import

![afterclickingimport](https://user-images.githubusercontent.com/33704272/38285903-0f80f378-3788-11e8-9056-e9073b35a338.JPG)

Plus I have been having a lot of trouble building the index which I think is needed when you have new vocabularies.  Here are some of the errors I am getting when trying to build the index

g.ohdsi.usagi.indexBuilding.ReadAthenaFile$AthenaFileIterator.readNext(Unknown Source)
org.ohdsi.usagi.indexBuilding.ReadAthenaFile$AthenaFileIterator.<init>(Unknown Source)
org.ohdsi.usagi.indexBuilding.ReadAthenaFile.iterator(Unknown Source)
org.ohdsi.usagi.indexBuilding.VocabVersionGrabber.grabVersion(Unknown Source)
org.ohdsi.usagi.indexBuilding.IndexBuildCoordinator$BuildThread.run(Unknown Source)

Recent vocabulary after extracting the zip file and running cpt.bat successfully.  Is anything missing from the vocabulary list that is trying to find?

![vocabulary_extraction](https://user-images.githubusercontent.com/33704272/38285997-98f0a2e8-3788-11e8-9b40-3131f25f5874.JPG)

**Comment by schuemie** [comment]
I'm sorry, I'm not able to reproduce the error you mention when building the index.  Your vocab folder looks the same as mine. Could you post the full error message?

There are two reasons why the genders are not mapped:

1. One limitation of the fuzzy string matching algorithm used by Usagi is that doesn't work with single-character queries. There's nothing I can do about it, but in theory you can only encounter that problem 26 times ;-) You can manually pick the right concepts later on.

2. Usagi only allows you to map to Standard concepts. (you can additionally map to Classification concepts if you uncheck 'Filter standard concepts') Only two concepts in the gender domain are standard according to the vocab: 8532 (Female) and 8507 (Male).

**Comment by anonymous34** [comment]
Hi I tried putting everything into a different folder and I was able to build the index.  I have a question about the source to concept map output.  The query for the vocabulary mapping contains this sql statement as part of the union:

SELECT source_code, SOURCE_CONCEPT_ID, SOURCE_CODE_DESCRIPTION, source_vocabulary_id, c1.domain_id AS SOURCE_DOMAIN_ID, c2.CONCEPT_CLASS_ID AS SOURCE_CONCEPT_CLASS_ID, c1.VALID_START_DATE AS SOURCE_VALID_START_DATE, c1.VALID_END_DATE AS SOURCE_VALID_END_DATE,stcm.INVALID_REASON AS SOURCE_INVALID_REASON,target_concept_id, c2.CONCEPT_NAME AS TARGET_CONCEPT_NAME, target_vocabulary_id, c2.domain_id AS TARGET_DOMAIN_ID, c2.concept_class_id AS TARGET_CONCEPT_CLASS_ID, c2.INVALID_REASON AS TARGET_INVALID_REASON, c2.standard_concept AS TARGET_STANDARD_CONCEPT
FROM source_to_concept_map stcm
**LEFT OUTER JOIN CONCEPT c1 ON c1.concept_id = stcm.source_concept_id**
LEFT OUTER JOIN CONCEPT c2 ON c2.CONCEPT_ID = stcm.target_concept_id
WHERE stcm.INVALID_REASON IS NULL

Since it is not exactly a 1 to 1 (our codes are not the exact same as the concept_code in the OMOP terminology) I decided to map using Usagi.  However, when I export the source to concept map file, the file is putting 0 for the source concept id.   With this query, the mapped Usagi codes will always have a source_concept_id of 0 correct and they would join to this record

Concept ID   Concept_Name               Domain_ID
0                   No Matching Concept    Metadata

I ask because we have a lot of custom codes and if there is not 1 to 1 concept_code match I assume we need to use Usagi to take care of these.

Is it recommended to use a different vocabulary_id then 'Ethnicity' like 200, 300 to differentiate from exact 1 to 1 matches in the vocabulary e.g. the values that would come from the first query in the union?  This query would be to map from source to source.  I know for standard we need to include a join to concept_relationship.

SELECT c.concept_code AS SOURCE_CODE, c.concept_id AS SOURCE_CONCEPT_ID, c.CONCEPT_NAME AS SOURCE_CODE_DESCRIPTION, c.vocabulary_id AS SOURCE_VOCABULARY_ID, c.domain_id 
AS SOURCE_DOMAIN_ID, c.concept_class_id AS SOURCE_CONCEPT_CLASS_ID, c.VALID_START_DATE AS SOURCE_VALID_START_DATE, c.VALID_END_DATE AS SOURCE_VALID_END_DATE, 
c.invalid_reason AS SOURCE_INVALID_REASON, c.concept_ID as TARGET_CONCEPT_ID, c.concept_name AS TARGET_CONCEPT_NAME, c.vocabulary_id AS TARGET_VOCABULARY_ID, 
c.domain_id AS TARGET_DOMAIN_ID, c.concept_class_id AS TARGET_CONCEPT_CLASS_ID, c.INVALID_REASON AS TARGET_INVALID_REASON,c.STANDARD_CONCEPT AS TARGET_STANDARD_CONCEPT
FROM CONCEPT c

**Comment by schuemie** [comment]
I'm not sure where you got the SQL that you refer to as 'The query for the vocabulary mapping', but it is not clear to me what it is for. Let me give some background to make sure we're on the same page:

Most of the times, people have codes that have already been mapped in the Vocabulary. In that case, the source codes will appear as concepts in the concept table, and their mapping to Standard Concepts is stored in the concept_relationship table. For example, ICD-10 codes are concepts in the concept table, and are mapped to Standard Concepts (mostly SNOMED) in the concept_relationship table. 

However, often people have codes that are not already mapped. In this case, you need to use the [source_to_concept_map table](https://github.com/OHDSI/CommonDataModel/wiki/SOURCE_TO_CONCEPT_MAP), and Usagi can be used to populate this table. In this table, you will store the mapping from your source codes to Standard Concepts. Your source codes will not have corresponding concepts in the concept table, and so source_concept_id will always be 0 (as prepopulated by Usagi). You need to come up with a unique vocabulary ID, for example 'jmdc_drugs', to make sure you later on know what types of codes are in the source_code field. 

The primary use of this source_to_concept_map is during your ETL, to identify the Standard Concept IDs to use when populating the CDM. Most OHDSI tools will rely solely on these Standard Concepts, and will ignore the source codes, even though they're also stored in the CDM. For example, the [drug_exposure table](https://github.com/OHDSI/CommonDataModel/wiki/DRUG_EXPOSURE) has a `drug_source_value` field where you can store your source code, a `drug_source_concept_id` field which, if you're source codes are not already in the Vocabulary will have the value 0, and a `drug_concept_id` field where you will store the Standard Concept ID that you identified as your best map using Usagi. 

Hope this helps.

**Comment by schuemie** [comment]
By definition, if the invalid_reason is not null then a concept cannot be a Standard Concept. So a target concept must have invalid_reason = null.

For source concepts this is different, and this has been the topic of a [recent discussion](http://forums.ohdsi.org/t/proposal-to-keep-outdated-standard-concepts-active-and-standard/3695). It was decided that source concepts that were valid in the past will now get invalid_reason = null, even if they are no longer valid. The date that the code become valid can be recorded in the valid_end_date field.
