### ISSUE TITLE
Suggested feature: sortable columns in results table

### ISSUE THREAD

**Issue by rsjaffe** [OHDSI/Usagi#46]
While many tables in usagi are sortable, the results table in the main window is not. There are instances in which it would be very useful to sort by something other than score--e.g., to look at other matches in the same concept class. Could the results table be made sortable? Thanks.

**Comment by schuemie** [comment]
This has been added in the [latest release](https://github.com/OHDSI/Usagi/releases/tag/v1.2.0).
