### ISSUE TITLE
issue about rebuilding the index

### ISSUE THREAD

**Issue by aushikun** [OHDSI/Usagi#48]
Hi, all

I was using the standard vocabulary file of drugs from OHDSI China to rebuild the index for mapping the Chinese local code. I encountered an error as below. I don't know how to solve the problem.

*** Generic error information ***
Message: null
Time: Jul 17, 2018 2:56:25 PM
Processor type: 
Available processors: 4
Maximum available memory: 1,908,932,608 bytes
Used memory: 26,264,224 bytes
Java version: 1.8.0_131
Java vendor: Oracle Corporation
OS architecture: x86_64
OS name: Mac OS X
OS version: 10.13.6
OS patch level: unknown

*** Stack trace ***
org.ohdsi.usagi.indexBuilding.ReadAthenaFile$AthenaFileIterator.readNext(Unknown Source)
org.ohdsi.usagi.indexBuilding.ReadAthenaFile$AthenaFileIterator.<init>(Unknown Source)
org.ohdsi.usagi.indexBuilding.ReadAthenaFile.iterator(Unknown Source)
org.ohdsi.usagi.indexBuilding.BerkeleyDbBuilder.loadAncestors(Unknown Source)
org.ohdsi.usagi.indexBuilding.BerkeleyDbBuilder.buildIndex(Unknown Source)
org.ohdsi.usagi.indexBuilding.IndexBuildCoordinator$BuildThread.run(Unknown Source)

*** Working folder contents ***
Directory of /Users/wangzhi/Program-test/usagi

ohdsi-drug-cn                                                                256      <DIR>        05-01-2018 02:50:04
Usagi_v1.1.5.jar                                                      19,144,874                   31-01-2018 10:35:37
Error.txt                                                                  1,324                   17-07-2018 02:55:38
sleepyCat                                                                    256      <DIR>        17-07-2018 02:56:25
Error1.txt                                                                     0                   17-07-2018 02:56:25

Available disc space: 18,948,526,080 bytes

**Comment by schuemie** [comment]
The error message suggests there's an issue with the CONCEPT_ANCESTOR.csv file. Does it have data?

**Comment by schuemie** [comment]
Thanks for letting us know how you resolved the problem!
