### ISSUE TITLE
issues uploading vocab in usagi

### ISSUE THREAD

**Issue by Tomy12** [OHDSI/Usagi#55]
Hello, 

So I have just started my OHDSI journey and downloaded Usagi to map with my vocabulary. However, when I direct it to the folder where the downloaded vocab is setting (from Athena). it stops at "building index. this will take a while.... Adding concepts to search index" it stays like this for days without changing 
I tired to close it and restart the process again but still facing the same issue.

Is it normal for Usagi to take that long to add concepts ?
![usagi issue](https://user-images.githubusercontent.com/46126245/50417384-10d30880-0837-11e9-8385-e9d2d4b0188a.png)

**Comment by Tomy12** [comment]
No worries... 
Solved the issue, apparently the device i was working on did not have JDK downloaded it and worked perfectly.

Thank you...

**Comment by schuemie** [comment]
Thanks for letting us know!
