### ISSUE TITLE
Writes out zero length file, causing loss of data.

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Usagi#56]
I had a mapping file I was working on.  I updated the vocabulary and created new indexes.  I then opened the file I had been working on, but when I saved the file I got the hourglass and the hourglass would not go away.  Closed Usagi and now the file I was working on was zero length.  Spent time looking into this.  The problem is a target concept id that is no longer valid, invalid reason = 'U'.   This caused an error in WriteCodeMappingToFile because the targetConcept.concept_id was NULL.  The write error did not display anywhere.

I stopped Usagi from having the NULL concept id by testing the concept in ReadCodeMappingsFromFile readNext(), after trying to get the concept, and only adding the concept if it was not NULL.  Probably not the best solution, but much better than loosing my file.

I think you can create a simple test case by having a file, with mappings to concepts, and then change one of the target concepts to an invalid value.  Then open the file in Usagi and then save the file.

**Comment by schuemie** [comment]
Yikes, sorry about that!

I know Usagi needs a lot more love when it comes to dealing with vocabulary and source code system updates, but we certainly can't have people lose data. So for now I fixed this issue in [this new release](https://github.com/OHDSI/Usagi/releases/tag/v1.2.2) by popping up a warning message and marking source codes with invalid concepts in red.
