### ISSUE TITLE
Usagi Asks Every User to Build the Index

### ISSUE THREAD

**Issue by anonymous34** [OHDSI/Usagi#57]
Hello,

We set up a virtual machine so that 1-4 users could log in and run the programs if needed.  I myself was able to successfully build the index in 3-4 hours.  However, another user wanted to log in and use the tool.  He went to the same directory on the C: drive and when he launched the application it asked him to build the index.  24 hours later it is still building the index.  Does the application need to be on his own machine to get it to work?  He is being delayed in helping us map source codes because of this.

**Comment by schuemie** [comment]
Usagi just checks if the `mainIndex` and `sleepyCat` folders exist in the same folder as the JAR file. If not, it asks to (re)build the index. That is independent of who the user is.

3-4 hours sounds like a really long time! Is the folder really on a local drive? Sometimes a "Documents" folder in Windows is actually on a network drive. Normally building the index takes about 10-15 minutes (on my laptop).

**Comment by anonymous34** [comment]
It is on a local drive.  The person is still having long run times when building the index.  It seems to be hanging at 'Adding concepts to search index'.  Is this an application where you cannot leave it running for awhile and come back later?  If I build the index on another computer and then copy everything over onto his computer a flash drive could that work or could something get messed up.

**Comment by schuemie** [comment]
Yes, if you build the index on one machine you can just copy the entire folder to a flash drive and run it somewhere else. Be sure to include the `mainIndex` and `sleepyCat` folders, as well as the text files that were generated like `DomainIds.txt` and `vocabularyVersion.txt`.

Building the search index is done using a third party library called Lucene that is usually very robust. Could you tell me what version and type of Java you're running? Is it Oracle Java (recommended)?

**Comment by anonymous34** [comment]
Thank you.  He is running Oracle java 1.8 .0_202-b08.
