### ISSUE TITLE
Usagi fails to open up

### ISSUE THREAD

**Issue by szelisk** [OHDSI/Usagi#58]
I have installed and re-installed Usagi about 10 times now.  I will get it to open and then start the building process.  Once the build is finished, it tells you to restart Usagi.  So I close Usagi and it will not open up again.  If I try by command line I get the message starting a new VM, then the prompt returns.

Anyone else having this issue?

**Comment by schuemie** [comment]
Others have recently reported similar problems with WhitRabbit,and one person reported to have solved it by installing a 64 bit version of Java (although it runs fine on 32 bits on my laptop). Could you try installing another Java version?

**Comment by szelisk** [comment]
I'm currently using Java 8, but I will load the newest one and let you know.

**Comment by schuemie** [comment]
I just released [a new version](https://github.com/OHDSI/Usagi/releases/tag/v1.2.7). Could you try that one? You don't have to rebuild the index. It is not going to solve your problem, but it should write any pertinent error messages to a file called 'ErrorStream.txt' in the same folder when you double-click the jar file. If you could share the contents of that file, we may see what is going on.

**Comment by szelisk** [comment]
I will try.

Thank you!
Susan
