### ISSUE TITLE
Cannot launch Usagi

### ISSUE THREAD

**Issue by yiminglight00** [OHDSI/Usagi#60]
Hi Martijn

My OS is Windows 10 (64-bit).
I have tried Java 32-bit and 64-bit.
I have also tried Usagi v1.2.7 and v1.2.8.
However, when I double-clicked Usagi, a command prompt window flashed and Usagi cannot be launched.
I have McAfee installed in my laptop.

May I know how I can solve this problem? 

Regards
Yi-Ming

**Comment by schuemie** [comment]
Could you check if a file called 'ErrorStream.txt' was created in the folder where the jar file is? If so, what does it say?

**Comment by yiminglight00** [comment]
Hi Martijn

There was no such file created when I downloaded Usagi. I only saw Usagi
jar file, and when I tried to open that jar file, I could not see anything.

Regards
Yi-Ming

Martijn Schuemie <notifications@github.com> 於 2019年6月6日 週四 16:23 寫道：

**Comment by schuemie** [comment]
Could you try running from the command prompt?
```
java -Xmx2000m -jar Usagi_v1.2.7.jar
```

**Comment by yiminglight00** [comment]
*Hi Martijn*

*It worked!*
*But I am wondering why double-click Usagi_v1.2.7.jar icon did not work?*

*Regards*
*Yi-Ming*

Martijn Schuemie <notifications@github.com> 於 2019年6月6日 週四 下午4:44寫道：
