### ISSUE TITLE
Applying old mapping

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Usagi#62]
When we apply an old mapping we get this message:

![](https://user-images.githubusercontent.com/7252105/67296443-c0751780-f4e8-11e9-8130-ce10f12c5ee3.png)

I assume this means that a target concept_id is not valid anymore. However, I do not see any red lines in the table. 

I would suggest to add a value in the status column that this code has to be re-mapped so you can sort on this.

**Comment by MaximMoinat** [comment]
Hi Peter, for me this works. See screenshot below. When sorting descending, the invalid concepts are on the top.

![image](https://user-images.githubusercontent.com/17825660/71670427-0fa0b980-2d70-11ea-9203-a8095ed2665a.png)

What I do miss, is some background; why is the mapping invalid? And what was the now invalid concept?

**Comment by MaximMoinat** [comment]
Just checked the code, and there is just one reason why a mapping is labeled 'Invalid Target', namely that the target concept cannot be found in the current indexed vocabulary.

https://github.com/OHDSI/Usagi/blob/c192ea987f2fd0b198865f59dc18b11a6a6c2f68/src/org/ohdsi/usagi/ReadCodeMappingsFromFile.java#L66-L73
