### ISSUE TITLE
Building initial index doesn't progress

### ISSUE THREAD

**Issue by liannekearsleyfleet** [OHDSI/Usagi#64]
When I point Usagi to the folder location for my vocabularies the message "building index" appears but doesn't change from 0% despite leaving overnight.

**Comment by liannekearsleyfleet** [comment]
![usagi](https://user-images.githubusercontent.com/49306680/71013593-d9650800-20e8-11ea-8299-43464dfb635a.jpg)

**Comment by MaximMoinat** [comment]
Building the index is a time and resource intensive task. What are your computer specs, in terms of processor, memory and available disk space?

And as a test you could you try with a subset of the vocabularies. e.g. by downloading only a few source vocabularies from Athena.

**Comment by EmV25** [comment]
I am having the same issue when opening the Usagi jar file by clicking on the shortcut. Loading in vocabularies doesn't proceed (I waited for a full day).
When I opened Usagi via the command line (`java -jar Usagi_*.jar`), and subsequently load in the vocabularies, it was finished in ~1 hour.

I am currently running Usagi v1.2.8 on a Windows OS.

**Comment by MaximMoinat** [comment]
Thanks! I have added this tip to the readme.
