### ISSUE TITLE
Add google search

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Usagi#66]
Would be nice if you could right click on a source field and do a google search (great if this is possible in a popup, otherwise in a browser window.

(note this repo does not allow tags to issues suggest to switch this on, this is a feature request)

**Comment by MaximMoinat** [comment]
May I suggest an alternative; making the source_term easy to copy to clipboard. Then at least with a simple ctrl-c, ctrl-v to your own browser, you can quickly search on the term.
