### ISSUE TITLE
Usagi Creating Duplicates in Exported STCM

### ISSUE THREAD

**Issue by anonymous34** [OHDSI/Usagi#67]
Hello,

I noticed in the export Usagi is creating duplicate records.  For example,  I see this row twice in the file:

![image](https://user-images.githubusercontent.com/33704272/72921676-57808400-3d11-11ea-81f7-72066da806c3.png)

and this one

![image](https://user-images.githubusercontent.com/33704272/72921758-7bdc6080-3d11-11ea-9732-aa30c52590ed.png)

The incoming frequency file did not have these source values twice.
I am on v1.2.7.  We plan to update the version soon.  Could this fix be in the next release?

Thank you

**Comment by MaximMoinat** [comment]
Hi, is it possible that you added the same concept twice as mapping target in Usagi? This would duplicate the record. See screenshot below how this could happen.

Might be a bit counterintuitive to allow a duplicate mapping. I'll check whether there might be some use case for this or that it should not be allowed by the UI.

![image](https://user-images.githubusercontent.com/17825660/74191028-91c7ac00-4c53-11ea-87b2-5ad597a095d8.png)

**Comment by MaximMoinat** [comment]
@anonymous34 Please verify whether the above is indeed what causes the behaviour you are observing.
