### ISSUE TITLE
Is This Tool Still Being Updated?

### ISSUE THREAD

**Issue by anonymous34** [OHDSI/Usagi#68]
The memory fix is still in pre-release from more than 6 months ago.  Is it okay to use it or do there need to be changes for the official release?  We need to map to the new vocabularies soon so I would like to avoid memory issues again.  Please let me know.  Also, I posted a topic about duplicate mapping showing up.

**Comment by MaximMoinat** [comment]
Hi anonymous34. This tool is indeed not actively being updated. That being said, the pre-release can be made into an official release. Thanks for reminding us!
