### ISSUE TITLE
Typo in "Vocbulary" version

### ISSUE THREAD

**Issue by alepev** [OHDSI/Usagi#69]
Once Usagi is open, you can see the current vocabulary version in the bottom-right corner. However, vocabulary is spelled "Vocbulary". Spotted in Usagi v1.2.8.

<img width="233" alt="Screenshot 2020-02-18 at 12 03 21" src="https://user-images.githubusercontent.com/32969540/74731372-25970a80-5248-11ea-9d95-42f4868f4af4.png">

**Comment by MaximMoinat** [comment]
Thanks for reporting, is already fixed and will be in the new release.
