### ISSUE TITLE
Index Building Errors

### ISSUE THREAD

**Issue by akiehl2000** [OHDSI/Usagi#70]
I have OHDSI-In-A-Box running on a virtual machine for exploratory purposes and I have a particular interest in utilizing Usagi. However, when I attempt to build an initial index from the following folder, I get the following nondescript error report. 
<img width="1419" alt="Screen Shot 2020-04-10 at 1 40 52 PM" src="https://user-images.githubusercontent.com/20071048/79018469-1f7b2700-7b31-11ea-8d39-7610906955e2.png">
<img width="1419" alt="Screen Shot 2020-04-10 at 1 40 06 PM" src="https://user-images.githubusercontent.com/20071048/79018461-1ab67300-7b31-11ea-8b41-24a488ef7e05.png">
All of the csv files are populated and exported from known, working OMOP vocabulary tables. Any ideas as to what this error means and how to overcome it?

**Comment by MaximMoinat** [comment]
Your 'TABLES' folder does not contain all the OMOP vocabulary files. In particular, the `VOCABULARY.csv` is missing. Usagi needs this to read in the vocabulary version.

Could you try again with a new, complete, download of the vocabularies from athena.org?
